// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RizzyCoBE.Models;

namespace RizzyCoBE.Migrations
{
    [DbContext(typeof(RizzyCoContext))]
    [Migration("20201207072937_SecondVersion")]
    partial class SecondVersion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RizzyCoBE.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int?>("TerritoryID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MapID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("TerritoryID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<int?>("MapID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MapID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Map", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAvailableArmies")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfContinents")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTerritories")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Mission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("Namse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MapID");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameID")
                        .HasColumnType("int");

                    b.Property<int?>("MissionID")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerColorID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("MissionID");

                    b.HasIndex("PlayerColorID");

                    b.HasIndex("UserID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RizzyCoBE.Models.PlayerColor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.ToTable("PlayerColors");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Territory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MapID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int?>("TerritoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MapID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("TerritoryID");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("RizzyCoBE.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Card", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Map", null)
                        .WithMany("Cards")
                        .HasForeignKey("MapID");

                    b.HasOne("RizzyCoBE.Models.Player", "Player")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerID");

                    b.HasOne("RizzyCoBE.Models.Territory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryID");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Game", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapID");

                    b.HasOne("RizzyCoBE.Models.User", null)
                        .WithMany("Games")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Mission", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Map", null)
                        .WithMany("Missions")
                        .HasForeignKey("MapID");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Player", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameID");

                    b.HasOne("RizzyCoBE.Models.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionID");

                    b.HasOne("RizzyCoBE.Models.PlayerColor", "PlayerColor")
                        .WithMany()
                        .HasForeignKey("PlayerColorID");

                    b.HasOne("RizzyCoBE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("RizzyCoBE.Models.PlayerColor", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Game", null)
                        .WithMany("PlayerColors")
                        .HasForeignKey("GameID");
                });

            modelBuilder.Entity("RizzyCoBE.Models.Territory", b =>
                {
                    b.HasOne("RizzyCoBE.Models.Map", null)
                        .WithMany("Territories")
                        .HasForeignKey("MapID");

                    b.HasOne("RizzyCoBE.Models.Player", "Player")
                        .WithMany("Territories")
                        .HasForeignKey("PlayerID");

                    b.HasOne("RizzyCoBE.Models.Territory", null)
                        .WithMany("Neighbours")
                        .HasForeignKey("TerritoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
